apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: "elasticsearch"
  replicas: {{ .Values.data.replicas }}
  selector:
    matchLabels:
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox:1.27.2
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 0
      containers:
      - name: es-data
        image: {{ .Values.image }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: {{ .Values.cluster_name | quote }}
        - name: xpack.monitoring.enabled
          value: {{ .Values.xpack.monitoring | quote }}
        - name: xpack.security.enabled
          value: {{ .Values.xpack.security | quote }}
        - name: bootstrap.memory_lock
          value: "false"
        - name: node.master
          value: "false"
        - name: node.data
          value: "true"
        - name: http.enabled
          value: {{ .Values.data.env.http | quote }}
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-discovery"
        - name: ES_JAVA_OPTS
          value: {{ .Values.data.env.java_opts }}
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: {{ .Values.storage.name }}
          mountPath: /usr/share/elasticsearch/data
#          subPathExpr: $(POD_NAME)
      volumes:
      - name: {{ .Values.storage.name }}
        persistentVolumeClaim:
           claimName: {{ .Values.storage.name }}
