apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: {{ .Values.master.replicas }}
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - master
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-master
        image: {{ .Values.image }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: {{ .Values.cluster_name | quote }}
        - name: xpack.monitoring.enabled
          value: {{ .Values.xpack.monitoring | quote }}
        - name: xpack.security.enabled
          value: {{ .Values.xpack.security | quote }}
        - name: node.master
          value: "true"
        - name: node.data
          value: "false"
        - name: node.ingest
          value: "false"
        - name: http.enabled
          value: {{ .Values.master.env.http | quote }}
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-discovery"
        - name: discovery.zen.minimum_master_nodes
          value: {{ .Values.master.env.discovery_zen_minimum_master_nodes | quote }}
        - name: ES_JAVA_OPTS
          value: {{ .Values.master.env.java_opts }}
        - name: node.max_local_storage_nodes
          value: {{ .Values.master.env.node_max_local_storage_nodes | quote }}
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: {{ .Values.master.limits.cpu }}
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
  selector:
    matchLabels:
      role: master
