apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.name }}
spec:
  capacity:
    storage: {{ .Values.storage.pv.size }}
  accessModes:
    - {{ .Values.storage.pv.mode }}
  mountOptions:
    - hard
    - nfsvers=4.2
    - timeo=60
    - retrans=10
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.storage.net.host }}
    path: {{ .Values.storage.net.path }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.name }}
spec:
  storageClassName: ""
  accessModes:
    - {{ .Values.storage.pv.mode }}
  resources:
    requests:
      storage: {{ .Values.storage.pv.size }}
