apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: es-client
spec:
  maxReplicas: {{ .Values.client.maxreplicas }}
  minReplicas: {{ .Values.client.minreplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: es-client
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.client.utilizationpercentage }}
