apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  annotations: 
    cloud.google.com/load-balancer-type: Internal
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: client
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
#  type: LoadBalancer
