apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    component: application
    role: ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: elasticsearch
              servicePort: 9200
            path: /elasticsearch(/|$)(.*)
