apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    component: application
    role: app
spec:
  selector:
    component: application
    role: app
  ports:
  - name: soap
    port: {{ .Values.port }}
    protocol: TCP
  clusterIP: None
