apiVersion: v1
kind: Service
metadata:
  name: ds-vol2
  labels:
    component: application
    role: ds-vol2
spec:
  selector:
    component: application
    role: ds-vol2
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
  clusterIP: None
