apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-head
  labels:
    component: application
    role: app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        component: application
        role: app
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      terminationGracePeriodSeconds: 0
      containers:
      - name: es-head
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.podPort }}
          name: es-head
