apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: es-head
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      expires 24h;
  labels:
    component: application
    role: ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: es-head
              servicePort: {{ .Values.podPort }}
            path: /eshead(/|$)(.*)
