apiVersion: v1
kind: Service
metadata:
  name: es-head
  labels:
    component: application
    role: es-head
spec:
  selector:
    component: application
    role: es-head
  ports:
  - name: es-head
    port: {{ .Values.podPort }}
    protocol: TCP
#  type: LoadBalancer
  clusterIP: None
